version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - db
    env_file:
      - .env
    command: ["./bot"]
    ports:
      - "8081:8081"
      - "6061:6061"
  app:
    build: .
    depends_on:
      - db
      - bot
    ports:
      - "8080:8080"
      - "6060:6060"
    env_file:
      - .env
    command: ["sh", "-c", "sleep 5 && goose -dir migrations up && /todo_list"]
